swagger: "2.0"
info:
  description: "Decompany Rest Api"
  version: "2019-02-15T09:19:49Z"
  title: "dev-backend-restapis"
  termsOfService: "https://www.google.com"
  contact:
    name: "Jay"
    email: "jay@decompany.io"
  license:
    name: "Decompany"
    url: "https://www.decompany.io"
host: "j5hgenjo04.execute-api.us-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /api/account/get:
    get:
      produces:
      - "application/json"
      responses: {}
  /api/account/picture:
    post:
      responses: {}
  /api/account/sync:
    post:
      responses: {}
      security:
      - accountAuth: []
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/account/update:
    post:
      responses: {}
  /api/curator/document/list:
    post:
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/curator/document/today:
    post:
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/document/download/{accountId}/{documentId}:
    get:
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/document/info/{documentId}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/document/list:
    post:
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/document/regist:
    post:
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/document/text/{documentId}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/document/vote/{documentId}:
    post:
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses: {}
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/oraclize/viewcount:
    get:
      responses: {}
  /api/tracking/collect:
    get:
      summary: "tracking collector"
      description: "collector for user's event tracking"
      produces:
      - "application/json"
      parameters:
      - name: "cid"
        in: "query"
        description: "client id"
        required: true
        type: "string"
      - name: "ev"
        in: "query"
        description: "event type [view, leave]"
        required: false
        type: "string"
      - name: "sid"
        in: "query"
        description: "session id"
        required: true
        type: "string"
      - name: "e"
        in: "query"
        description: "email"
        required: false
        type: "string"
      - name: "t"
        in: "query"
        description: "event timestamp"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/DefaultResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/tracking/info:
    get:
      summary: "tracking summary list"
      description: "tracking summary list"
      produces:
      - "application/json"
      parameters:
      - name: "documentid"
        in: "query"
        description: "document id"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/DefaultResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /api/tracking/list:
    get:
      summary: "tracking detail list"
      description: "tracking detail list"
      produces:
      - "application/json"
      parameters:
      - name: "cid"
        in: "query"
        description: "client id"
        required: true
        type: "string"
      - name: "sid"
        in: "query"
        description: "session id"
        required: true
        type: "string"
      - name: "documentid"
        in: "query"
        description: "document id"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/DefaultResponse"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Credentials:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
securityDefinitions:
  accountAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
definitions:
  DefaultResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
      resultList:
        type: "array"
    title: "ResponseModel"
    description: "default response"
