# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: batch-pageview # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-1
  stage: ${opt:stage, 'dev'}
  vpc:
    securityGroupIds:
      - sg-05a13849fc117801b
    subnetIds:
      - subnet-37594850
      - subnet-38bb9963
  environment:
    stage: ${self:provider.stage}
    region: ${self:provider.region}
    servicename: ${self:service.name}
  logRetentionInDays: 3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - s3:*
       - logs:*
       - sqs:*
       - kinesis:*
       - events:*
       - kms:*
      Resource: "*"   
  exclude:
    - .gitignore
    - .env

functions:
  onchainWritePageview:
    handler: functions/onchain/writePageview.handler
    timeout: 300 # optional, in seconds, default is 6, 5min
    reservedConcurrency: 1
    events:
      - sqs:
          arn: arn:aws:sqs:us-west-1:197966029048:DEV-CA-SC-VIEWCOUNT
#          batchSize: 1
#          enabled: true

  pageviewRequestWritePageview:
    handler: functions/pageview/requestWritePageview.handler
    timeout: 300
    events:
      - schedule: cron(10 0 * * ? *) # daily 00:10:00

  pageviewByHourly:
    handler: functions/pageview/hourly.handler
    timeout: 300
    events:
      - schedule: rate(1 hour) # 10min, hourly

plugins:
  - serverless-mocha-plugin